nome = str(input('Digite sue nome completo: ')).strip()
print('Analizando seu nome...')
print(f'Seu nome em maiúsculas é {nome.upper()}')
print(f'Seu nome em minúsculo é {nome.lower()}')
print(f'Seu nome tem ao todo {len(nome) - nome.count(" ")}')
print(f'Seu primeiro nome tem {nome.find(" ")}')
print('Outra forma de fazer...')
separa = nome.split()
print(f'Seu primeiro no me é {separa[0]} e ele tem {len(separa[0])} letras')
